# Excercise # 01 (Transaction Data Analysis with Pandas)

In [ ]:
import pandas as pd

In [ ]:
t = pd.read_csv('Transactions.csv', dtype={'committer':'str','receiver':'str'}, header=None,names = ['id','amount','committer','receiver','type'])

In [ ]:
t.head(5)

   id  amount committer receiver           type
0   1    3450       872      516  bank transfer
1   2     505       989      NaN    credit card
2   3   11320       178      702  bank transfer
3   4    9325       729      378         cheque
4   5     620       706      NaN    credit card

## Bank Transfer Transactions:

In [ ]:
def bank_transfer_transactions():
  bank_transfer_t = t[t['type']=='bank transfer']
  return bank_transfer_t

In [ ]:
bank_transfer_t = bank_transfer_transactions()

In [ ]:
bank_transfer_t

    id  amount committer receiver           type
0    1    3450       872      516  bank transfer
2    3   11320       178      702  bank transfer
5    6    5775       842      127  bank transfer
6    7    7255       713      136  bank transfer
8    9    7250       979      247  bank transfer
9   10   36545       648      843  bank transfer
12  13   11100        66       35  bank transfer
16  17   21575       760      919  bank transfer
17  18   14710       889      828  bank transfer

## User-Specific Transactions:

In [ ]:
def user_spec_trans(committer='323'):
  user_spec_t = t[t['committer']==committer]
  return user_spec_t

In [ ]:
user_spec_t = user_spec_trans()

In [ ]:
user_spec_t

Empty DataFrame
Columns: [id, amount, committer, receiver, type]
Index: []

## Multiple Specific Transactions:

In [ ]:
def mult_spec_trans(committer_1='323',committer_2='194'):
  mult_spec_t = t[(t['committer']==committer_1) | (t['committer']==committer_2)]
  return mult_spec_t

In [ ]:
mult_spec_t = mult_spec_trans()

In [ ]:
mult_spec_t

Empty DataFrame
Columns: [id, amount, committer, receiver, type]
Index: []

## Aggregated Transaction Amounts:

In [ ]:
def agg_trans_amount():
  value = t[(t['type']=='credit card') | (t['type']=='cheque')]
  agg_t_amount = value['amount'].sum()
  return agg_t_amount

In [ ]:
agg_t_amount = agg_trans_amount()

In [ ]:
print(f'Aggregated Transaction Amounts: {agg_t_amount}')

Aggregated Transaction Amounts: 108495

## Filtered Transaction Range:

In [ ]:
def filt_trans_range():
  filt_t_range  = t[(t['type']=='bank transfer') & (t['id'].between(1,10))]
  return filt_t_range

In [ ]:
filt_t_range = filt_trans_range()

In [ ]:
filt_t_range

   id  amount committer receiver           type
0   1    3450       872      516  bank transfer
2   3   11320       178      702  bank transfer
5   6    5775       842      127  bank transfer
6   7    7255       713      136  bank transfer
8   9    7250       979      247  bank transfer
9  10   36545       648      843  bank transfer

## High-Value Bank Transfers:

In [ ]:
def high_v_bank_trans():
  high_value = t[(t['type']=='bank transfer') & (t['amount']>10000)]
  return high_value

In [ ]:
high_value = high_v_bank_trans()

In [ ]:
high_value

    id  amount committer receiver           type
2    3   11320       178      702  bank transfer
9   10   36545       648      843  bank transfer
12  13   11100        66       35  bank transfer
16  17   21575       760      919  bank transfer
17  18   14710       889      828  bank transfer

# Excercise # 02 (Data Integration and Analysis with Pandas)

In [ ]:
import pandas as pd

In [ ]:
t_2 = pd.read_csv('Transactions2.csv',sep=';',dtype={'committer':'str','receiver':'str'},header=None,names = ['id','amount','committer','receiver','type'])

In [ ]:
t_2.head(5)

   id  amount committer receiver           type
0   0    3450       872      516  bank transfer
1   1     505       989      NaN    credit card
2   2   11320       178      702  bank transfer
3   3    9325       729      378         cheque
4   4     620       706      NaN    credit card

In [ ]:
s = pd.read_excel('subjects.xlsx', dtype={'ID':'str','OLDID':'str'})

In [ ]:
s.head(5)

,OLDID,ID,LASTNAME,FIRSTNAME,BIRTHDAY,BIRTHMONTH,BIRTHYEAR,GENDER,STREET ADDRESS,CAP,CITY,LATITUDE,LONGITUDE
0,34,35,Bianchini,Vincenza,9,5,1987,Female,"Piazza Centrale, 21",10070,ALA DI STURA,45.306841,7.282311
1,65,66,Gherardi,Cristina,9,10,1986,Female,"Via Trasimeno, 5/b",6034,FOLIGNO,42.956182,12.703334
2,77,78,Tinti,Attilio,25,10,1987,Male,-,81031,AVERSA,40.973212,14.204928
3,126,127,Piazzi,Lara,28,7,1987,Female,"Via Conciliazione, 61",20024,GARBAGNATE MILANESE,45.575246,9.079421
4,135,136,D'amico,Manuel,23,3,1983,Male,"Corso V. Emanuele, 31",84010,MINORI,40.659413,14.625402

In [ ]:
s.drop(columns='OLDID', inplace=True)

In [ ]:
replacements = {'Female':'F','Male':'M'}
s['GENDER'].replace(replacements, inplace=True)
s

,ID,LASTNAME,FIRSTNAME,BIRTHDAY,BIRTHMONTH,BIRTHYEAR,GENDER,STREET ADDRESS,CAP,CITY,LATITUDE,LONGITUDE
0,35,Bianchini,Vincenza,9,5,1987,F,"Piazza Centrale, 21",10070,ALA DI STURA,45.306841,7.282311
1,66,Gherardi,Cristina,9,10,1986,F,"Via Trasimeno, 5/b",6034,FOLIGNO,42.956182,12.703334
2,78,Tinti,Attilio,25,10,1987,M,-,81031,AVERSA,40.973212,14.204928
3,127,Piazzi,Lara,28,7,1987,F,"Via Conciliazione, 61",20024,GARBAGNATE MILANESE,45.575246,9.079421
4,136,D'amico,Manuel,23,3,1983,M,"Corso V. Emanuele, 31",84010,MINORI,40.659413,14.625402
5,143,Ravaglia,Adriana,16,5,1985,F,"Corso Alessandro Tassoni, 66/D",10144,TORINO,45.070920,7.685972
6,178,Romano,Elio,1,3,1987,M,"Via Genazzano,45",38,VALMONTONE,41.775622,12.926422
7,194,Bentivogli,Gabriele,28,6,1987,M,"Via G. Cesare, 70",80125,NAPOLI,40.850696,14.246317
8,239,Serafini,Emiliano,17,8,1984,M,"Via Gazzoletti, 3",20157,MILANO,45.518149,9.136979
9,247,Biagini,Angiolina,28,11,1988,F,"Via di Tiglio, 742",55100,LUCCA,43.833341,10.546148
10,275,Bruni,Alex,22,11,1986,M,Via M. Greco,88100,CATANZARO,38.891443,16.603167
11,279,Piazzi,Maria Cristina,10,8,1983,F,"Piazza della Liberta, 13",15079,SEZZADIO,44.793869,8.566804
12,323,Leone,Sara,20,1,1986,F,"P.le Loreto, 7",20131,MILANO,45.486245,9.216670
13,378,Cremonini,Tiziano,11,13,1988,M,"Via Di Vittorio, 2",21029,VERGIATE,45.731488,8.699933
14,413,Trombetti,Nino,19,12,1983,M,"Loc. Centro, 98",39010,TESIMO,46.563898,11.169497
15,437,Vivarelli,Pietro,26,9,1983,M,"Via Cesare Battisti, 29",25079,VOBARNO,45.671313,10.501194
16,443,Rizzi,Moreno,7,8,1986,M,"Via IV Novembre, 1",73030,CASTRO,40.009614,18.422351
17,484,Bolognini,Arianna,7,2,1988,F,"Via Calace, 54",70052,BISCEGLIE,41.240274,16.501011
18,516,Rossetti,Domenico,28,2,1985,M,"Via Trieste, 20",20092,CINISELLO BALSAMO,45.557393,9.218068
19,648,Nascetti,Amelia,1,11,1984,F,"Piazza Giacomo Gregis, 10",24060,GORLAGO,45.671637,9.833693
20,664,Parisini,Walther,13,8,1983,M,Viale Pola 63,72017,OSTUNI,40.727220,17.575976
21,702,Monari,Gabriella,14,9,1989,F,"Via Asseggiano, 258",30030,VENEZIA,45.493369,12.204945
22,706,Cavazza,Ilaria,8,3,1985,F,"Via Raffaele Morghen, 165",80129,NAPOLI,40.844090,14.234772
23,713,Marchi,Cinzia,24,8,1984,F,"Via Santa Caterina, 108",80053,CASTELLAMMARE DI STABIA,40.693065,14.510346
24,716,Tinarelli,Michelangelo,17,3,1986,M,"Via Maggiore, 6",48100,RAVENNA,44.420799,12.190443
25,729,Faggioli,Enzo,13,7,1988,M,-,89054,GALATRO,38.463812,16.165836
26,759,Billi,Angiolina,29,5,1983,F,"Via Cottolengo, 1",10064,PINEROLO,44.885654,7.320843
27,760,Minarini,Maria Pia,22,12,1989,F,"Viale Roma, 7",21020,DAVERIO,45.773503,8.768916
28,796,Bonazzi,Alberto,8,4,1988,M,Via Calderaio,51010,MASSA E COZZILE,43.906394,10.751723
29,828,Parisi,Sandro,3,10,1983,M,"Via San Carlo, 7",28831,BAVENO,45.940862,8.466423
30,842,Matteuzzi,Cesarina,27,4,1984,F,"Via Colonnello Elia, 34",73020,MELENDUGNO,40.241873,18.377608
31,843,Calzolari,Pierina,14,11,1986,F,"Via Centrale, 9",82010,BUCCIANO,41.082859,14.579031
32,872,Mascagni,Virginia,15,8,1987,F,"Via Della Resistenza, 30",20068,PESCHIERA BORROMEO,45.442331,9.302962
33,889,Salmi,Piero,22,9,1984,M,"Via Castellana, 99/q",30174,VENEZIA,45.506397,12.457370
34,919,Tartarini,Sebastiano,1,12,1989,M,"Via Don Minzoni, 1",44023,LAGOSANTO,44.771096,12.144113
35,944,Martini,Sauro,21,9,1986,M,"Via Roma, 20",56126,PISA,43.764593,10.438080
36,964,Lippi,Emma,10,12,1986,F,"Via Ornato, 13/A",20162,MILANO,45.466621,9.190617
37,979,Guerzoni,Adriano,9,10,1983,M,"Via Provinciale, 15",43010,LANGHIRANO,44.615417,10.234199
38,989,Stagni,Domenica,26,9,1988,F,"Via Gravellona, 36/A",27029,VIGEVANO,45.323182,8.831745

In [ ]:
s['BIRTHDATE'] = pd.to_datetime(s['BIRTHDAY'].astype(str)+'/'+s['BIRTHMONTH'].astype(str)+'/'+s['BIRTHYEAR'].astype(str))
s.drop(columns=['BIRTHYEAR','BIRTHDAY','BIRTHMONTH'], inplace=True)

<ipython-input-74-9785123f862c>:1: UserWarning: Parsing dates in DD/MM/YYYY format when dayfirst=False (the default) was specified. This may lead to inconsistently parsed dates! Specify a format to ensure consistent parsing.
  s['BIRTHDATE'] = pd.to_datetime(s['BIRTHDAY'].astype(str)+'/'+s['BIRTHMONTH'].astype(str)+'/'+s['BIRTHYEAR'].astype(str))

In [ ]:
s

,ID,LASTNAME,FIRSTNAME,GENDER,STREET ADDRESS,CAP,CITY,LATITUDE,LONGITUDE,BIRTHDATE
0,35,Bianchini,Vincenza,F,"Piazza Centrale, 21",10070,ALA DI STURA,45.306841,7.282311,1987-09-05
1,66,Gherardi,Cristina,F,"Via Trasimeno, 5/b",6034,FOLIGNO,42.956182,12.703334,1986-09-10
2,78,Tinti,Attilio,M,-,81031,AVERSA,40.973212,14.204928,1987-10-25
3,127,Piazzi,Lara,F,"Via Conciliazione, 61",20024,GARBAGNATE MILANESE,45.575246,9.079421,1987-07-28
4,136,D'amico,Manuel,M,"Corso V. Emanuele, 31",84010,MINORI,40.659413,14.625402,1983-03-23
5,143,Ravaglia,Adriana,F,"Corso Alessandro Tassoni, 66/D",10144,TORINO,45.070920,7.685972,1985-05-16
6,178,Romano,Elio,M,"Via Genazzano,45",38,VALMONTONE,41.775622,12.926422,1987-01-03
7,194,Bentivogli,Gabriele,M,"Via G. Cesare, 70",80125,NAPOLI,40.850696,14.246317,1987-06-28
8,239,Serafini,Emiliano,M,"Via Gazzoletti, 3",20157,MILANO,45.518149,9.136979,1984-08-17
9,247,Biagini,Angiolina,F,"Via di Tiglio, 742",55100,LUCCA,43.833341,10.546148,1988-11-28
10,275,Bruni,Alex,M,Via M. Greco,88100,CATANZARO,38.891443,16.603167,1986-11-22
11,279,Piazzi,Maria Cristina,F,"Piazza della Liberta, 13",15079,SEZZADIO,44.793869,8.566804,1983-10-08
12,323,Leone,Sara,F,"P.le Loreto, 7",20131,MILANO,45.486245,9.216670,1986-01-20
13,378,Cremonini,Tiziano,M,"Via Di Vittorio, 2",21029,VERGIATE,45.731488,8.699933,1988-11-13
14,413,Trombetti,Nino,M,"Loc. Centro, 98",39010,TESIMO,46.563898,11.169497,1983-12-19
15,437,Vivarelli,Pietro,M,"Via Cesare Battisti, 29",25079,VOBARNO,45.671313,10.501194,1983-09-26
16,443,Rizzi,Moreno,M,"Via IV Novembre, 1",73030,CASTRO,40.009614,18.422351,1986-07-08
17,484,Bolognini,Arianna,F,"Via Calace, 54",70052,BISCEGLIE,41.240274,16.501011,1988-07-02
18,516,Rossetti,Domenico,M,"Via Trieste, 20",20092,CINISELLO BALSAMO,45.557393,9.218068,1985-02-28
19,648,Nascetti,Amelia,F,"Piazza Giacomo Gregis, 10",24060,GORLAGO,45.671637,9.833693,1984-01-11
20,664,Parisini,Walther,M,Viale Pola 63,72017,OSTUNI,40.727220,17.575976,1983-08-13
21,702,Monari,Gabriella,F,"Via Asseggiano, 258",30030,VENEZIA,45.493369,12.204945,1989-09-14
22,706,Cavazza,Ilaria,F,"Via Raffaele Morghen, 165",80129,NAPOLI,40.844090,14.234772,1985-08-03
23,713,Marchi,Cinzia,F,"Via Santa Caterina, 108",80053,CASTELLAMMARE DI STABIA,40.693065,14.510346,1984-08-24
24,716,Tinarelli,Michelangelo,M,"Via Maggiore, 6",48100,RAVENNA,44.420799,12.190443,1986-03-17
25,729,Faggioli,Enzo,M,-,89054,GALATRO,38.463812,16.165836,1988-07-13
26,759,Billi,Angiolina,F,"Via Cottolengo, 1",10064,PINEROLO,44.885654,7.320843,1983-05-29
27,760,Minarini,Maria Pia,F,"Viale Roma, 7",21020,DAVERIO,45.773503,8.768916,1989-12-22
28,796,Bonazzi,Alberto,M,Via Calderaio,51010,MASSA E COZZILE,43.906394,10.751723,1988-08-04
29,828,Parisi,Sandro,M,"Via San Carlo, 7",28831,BAVENO,45.940862,8.466423,1983-03-10
30,842,Matteuzzi,Cesarina,F,"Via Colonnello Elia, 34",73020,MELENDUGNO,40.241873,18.377608,1984-04-27
31,843,Calzolari,Pierina,F,"Via Centrale, 9",82010,BUCCIANO,41.082859,14.579031,1986-11-14
32,872,Mascagni,Virginia,F,"Via Della Resistenza, 30",20068,PESCHIERA BORROMEO,45.442331,9.302962,1987-08-15
33,889,Salmi,Piero,M,"Via Castellana, 99/q",30174,VENEZIA,45.506397,12.457370,1984-09-22
34,919,Tartarini,Sebastiano,M,"Via Don Minzoni, 1",44023,LAGOSANTO,44.771096,12.144113,1989-01-12
35,944,Martini,Sauro,M,"Via Roma, 20",56126,PISA,43.764593,10.438080,1986-09-21
36,964,Lippi,Emma,F,"Via Ornato, 13/A",20162,MILANO,45.466621,9.190617,1986-10-12
37,979,Guerzoni,Adriano,M,"Via Provinciale, 15",43010,LANGHIRANO,44.615417,10.234199,1983-09-10
38,989,Stagni,Domenica,F,"Via Gravellona, 36/A",27029,VIGEVANO,45.323182,8.831745,1988-09-26

## Committer Variables in Subjects Dataframe

In [ ]:
def committer_subject_dataframe():
  s['committer'] = False
  for comm_uniq in list(t_2['committer'].unique()):
    if s['ID'][s['ID']==comm_uniq].count() >=1:
      s['committer'][s['ID']==comm_uniq] = True
    else:
      s['committer'][s['ID']==comm_uniq] = False

In [ ]:
committer_subject_dataframe()

<ipython-input-127-80bfeb1563a3>:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['committer'][s['ID']==comm_uniq] = True
<ipython-input-127-80bfeb1563a3>:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  s['committer'][s['ID']==comm_uniq] = False

In [ ]:
s.head()

,ID,LASTNAME,FIRSTNAME,GENDER,STREET ADDRESS,CAP,CITY,LATITUDE,LONGITUDE,BIRTHDATE,committer
0,35,Bianchini,Vincenza,F,"Piazza Centrale, 21",10070,ALA DI STURA,45.306841,7.282311,1987-09-05,True
1,66,Gherardi,Cristina,F,"Via Trasimeno, 5/b",6034,FOLIGNO,42.956182,12.703334,1986-09-10,True
2,78,Tinti,Attilio,M,-,81031,AVERSA,40.973212,14.204928,1987-10-25,True
3,127,Piazzi,Lara,F,"Via Conciliazione, 61",20024,GARBAGNATE MILANESE,45.575246,9.079421,1987-07-28,True
4,136,D'amico,Manuel,M,"Corso V. Emanuele, 31",84010,MINORI,40.659413,14.625402,1983-03-23,True

## Tax Variables in Transection Dataframes

In [ ]:
t_2.head(5)

   id  amount committer receiver           type
0   0    3450       872      516  bank transfer
1   1     505       989      NaN    credit card
2   2   11320       178      702  bank transfer
3   3    9325       729      378         cheque
4   4     620       706      NaN    credit card

In [ ]:
import numpy as np

In [ ]:
def tax_transection_dataframe():
  t_2['tax']=0.0
  t_2['tax'] = np.where(t_2['type'] == 'bank transfer', t_2['amount'] * 0.02,
                    np.where(t_2['type'] == 'credit card', t_2['amount'] * 0.03, 0.0))

In [ ]:
tax_transection_dataframe()

In [ ]:
t_2.head(5)

   id  amount committer receiver           type     tax
0   0    3450       872      516  bank transfer   69.00
1   1     505       989      NaN    credit card   15.15
2   2   11320       178      702  bank transfer  226.40
3   3    9325       729      378         cheque    0.00
4   4     620       706      NaN    credit card   18.60

## Transection Counts and Tax Amounts

In [ ]:
def trans_count_tax_amount():
  t_count_tax_amount = t_2.groupby('receiver').agg({'id': 'count', 'tax': 'sum'}).reset_index()
  t_count_tax_amount.rename(columns={'receiver':'receiver_id','id': 'total_received_transactions', 'tax': 'total_taxes_paid'}, inplace=True)
  return t_count_tax_amount

In [ ]:
t_count_tax_amount = trans_count_tax_amount()

In [ ]:
t_count_tax_amount

    receiver_id  total_received_transactions  total_taxes_paid
0           107                            1              0.00
1           119                            1              0.00
2           127                            9           1137.62
3           128                            1            548.40
4           130                            1           1095.80
..          ...                          ...               ...
207         982                            1              0.00
208         991                            1             68.74
209         993                            2           1084.34
210         994                            2              0.00
211         997                            1              0.00

[212 rows x 3 columns]

## Export Tax Summary

In [ ]:
def save_tax_summary(t_count_tax_amount,file_name='tax_summary.xlsx'):
  total_tax = []
  for id in list(s['ID'].values):
    if list(t_count_tax_amount['total_taxes_paid'][t_count_tax_amount['receiver_id']==id].values) == []:
      total_tax.append(0.0)
    else:
      total_tax.append(list(t_count_tax_amount['total_taxes_paid'][t_count_tax_amount['receiver_id']==id].values)[0])


  data = {
      "ID number":s['ID'].values,
      "first name":s['FIRSTNAME'].values,
      "last name":s['LASTNAME'].values,
      "total amount of taxes paid":total_tax,

  }
  df = pd.DataFrame(data)

  # Save the DataFrame to an Excel file
  output_file = file_name
  df.to_excel(output_file, index=False)

  print(f"DataFrame saved to {output_file}")

In [ ]:
save_tax_summary(t_count_tax_amount)

DataFrame saved to tax_summary.xlsx